#!/usr/bin/env node
/*
 * Builds src/share-template.js: the whole app (page, styles, fonts, scripts)
 * as one HTML string. "Share as file" fills it with the selected swimmers and
 * downloads it, so the receiver gets a page that works with no website.
 *
 *   node tools/build-share.js        (npm run build-share)
 *
 * The output is generated, not committed: CI builds it before every deploy.
 * It's needed because the app's Content Security Policy stops the page from
 * reading its own files at run time (connect-src 'none').
 *
 * The shared page keeps the same guarantees: its CSP allows only these exact
 * inline scripts (by SHA-256 hash), embedded fonts, and no network at all.
 * Placeholders <!--SHARE:name--> are filled in by app.js.
 */
"use strict";
const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");

const ROOT = path.resolve(__dirname, "..");
const OUT = path.join(ROOT, "src", "share-template.js");
const SCRIPTS = ["vendor/jszip.min.js", "src/cl2.js", "src/session.js", "src/app.js"];
const read = p => fs.readFileSync(path.join(ROOT, p), "utf8");

function replaceOnce(html, from, to){
  const i = typeof from === "string" ? html.indexOf(from) : html.search(from);
  if (i < 0) throw new Error(`build-share: index.html no longer contains ${from}; update tools/build-share.js`);
  return typeof from === "string" ? html.slice(0, i) + to + html.slice(i + from.length) : html.replace(from, () => to);
}

function buildTemplate(){
  const css = read("src/styles.css").replace(/url\("\.\.\/vendor\/fonts\/([\w.-]+\.woff2)"\)/g, (_, f) =>
    `url("data:font/woff2;base64,${fs.readFileSync(path.join(ROOT, "vendor", "fonts", f)).toString("base64")}")`);
  if (/url\("\.\./.test(css)) throw new Error("build-share: styles.css has a url() that isn't an embeddable font");

  // "</script" would end the inline script early; "<!--" changes how browsers parse script text
  const scripts = SCRIPTS.map(p => {
    const js = read(p).replace(/<\/script/gi, "<\\/script");
    if (js.includes("<!--")) throw new Error(`build-share: ${p} contains "<!--", which breaks inline scripts`);
    return js;
  });
  const hashes = scripts.map(js => `'sha256-${crypto.createHash("sha256").update(js, "utf8").digest("base64")}'`);
  const csp = `default-src 'none'; script-src ${hashes.join(" ")}; style-src 'unsafe-inline'; font-src data:; ` +
              `img-src data: blob:; connect-src 'none'; object-src 'none'; base-uri 'none'; form-action 'none'`;

  let html = read("index.html");
  html = replaceOnce(html, '<html lang="en">', '<html lang="en" class="nojs">');
  html = replaceOnce(html, /<meta http-equiv="Content-Security-Policy" content="[^"]*">/,
    `<meta http-equiv="Content-Security-Policy" content="${csp}">`);
  html = replaceOnce(html, "<title>Best Times — CL2 Viewer</title>", "<title>Best Times (shared)</title>");
  html = replaceOnce(html, '<link rel="stylesheet" href="src/styles.css">', `<style>\n${css}</style>`);
  html = replaceOnce(html, "<body>", `<body class="shared">
<div id="sharednote"><b>Shared best times</b>, made with swimtimescoach.com on <!--SHARE:date-->. Everything in this file stays on your device.
  <span class="nojs-only">Tap a time to see every swim. To switch views, pick swimmers or add meets, open this file in a web browser, or go to <b>swimtimescoach.com</b>, tap <b>Open session</b> and choose this file.</span></div>`);
  html = replaceOnce(html, '<div id="files"></div>', '<div id="files"><!--SHARE:files--></div>');
  html = replaceOnce(html, '<div class="wrap" id="wrap"><div class="empty">No results loaded yet.</div></div>',
    '<div class="wrap" id="wrap"><!--SHARE:wrap--></div>');
  html = replaceOnce(html, '<div id="appendix"></div>', '<div id="appendix"></div>\n<div id="sdetails"><!--SHARE:details--></div>');
  SCRIPTS.forEach((p, i) => {
    const data = i === 0 ? '<script type="text/plain" id="sharedSession"><!--SHARE:data--></script>\n' : "";
    html = replaceOnce(html, `<script src="${p}"></script>`, `${data}<script>${scripts[i]}</script>`);
  });
  if (/\b(src|href)="(?!data:)[^"#]/.test(html)) throw new Error("build-share: template still references an outside file");
  return html;
}

function main(){
  const html = buildTemplate();
  fs.writeFileSync(OUT, "// Generated by tools/build-share.js; don't edit or commit.\nwindow.SHARE_TEMPLATE = " + JSON.stringify(html) + ";\n");
  console.log(`Wrote ${path.relative(ROOT, OUT)} (${Math.round(fs.statSync(OUT).size / 1024)} KB)`);
}

module.exports = { buildTemplate };
if (require.main === module) main();
